import React, {useEffect, useMemo, useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
import {Search, Heart, MessageCircle, Plus, ShieldCheck, Menu, X, ArrowRight, Tag, LogOut} from "lucide-react";
import "./styles.css";

const supabaseUrl=import.meta.env.VITE_SUPABASE_URL;
const supabaseKey=import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase=(supabaseUrl&&supabaseKey&&supabaseUrl!=="your_supabase_project_url")?createClient(supabaseUrl,supabaseKey):null;

const demo=[
 {id:"demo-1",title:"Vintage Denim Jacket",price:8000,category:"Thrift/Fashion",condition:"Good",location:"LASU",seller:"CampusSeller",seller_id:null,image:"https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=80"},
 {id:"demo-2",title:"HP EliteBook Laptop",price:185000,category:"Electronics",condition:"Good",location:"Oto-Ijanikin",seller:"TechStudent",seller_id:null,image:"https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80"},
 {id:"demo-3",title:"Engineering Mathematics Book",price:4500,category:"Books",condition:"Good",location:"LASU",seller:"BookPlug",seller_id:null,image:"https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=900&q=80"},
 {id:"demo-4",title:"Bluetooth Headphones",price:12000,category:"Electronics",condition:"Like New",location:"Lagos",seller:"SoundHub",seller_id:null,image:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=80"}
];

const first=(...v)=>v.find(x=>x!==undefined&&x!==null&&x!=="");
function mapListing(row){
 const image=first(row.image_url,row.image,row.thumbnail_url,row.photo_url);
 return {id:row.id,title:first(row.title,row.name,"Untitled listing"),price:Number(first(row.price,0)),category:first(row.category,"Other"),condition:first(row.condition,"Good"),location:first(row.location,row.city,"Campus"),seller_id:first(row.seller_id,row.user_id,row.owner_id,row.created_by),seller:first(row.seller_name,row.seller,"Seller"),description:first(row.description,""),image};
}

function App(){
 const [page,setPage]=useState("home"),[products,setProducts]=useState(demo),[query,setQuery]=useState(""),[category,setCategory]=useState("All"),[menu,setMenu]=useState(false),[favorites,setFavorites]=useState([]),[selectedListing,setSelectedListing]=useState(null),[user,setUser]=useState(null);
 const cats=["All","Thrift/Fashion","Electronics","Books","School Supplies","Accessories","Food","Accommodation","Services"];
 useEffect(()=>{
   if(!supabase)return;
   supabase.auth.getUser().then(({data})=>setUser(data.user||null));
   const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,session)=>setUser(session?.user||null));
   return()=>subscription.unsubscribe();
 },[]);
 useEffect(()=>{loadListings();},[]);
 const loadListings=async()=>{
   if(!supabase)return;
   const {data,error}=await supabase.from("listings").select("*").order("created_at",{ascending:false});
   if(!error&&data?.length)setProducts(data.map(mapListing));
 };
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category===category)&&(`${p.title} ${p.description||""} ${p.category} ${p.location||""}`.toLowerCase().includes(query.toLowerCase()))),[products,query,category]);
 const nav=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:"smooth"})};
 const openProduct=p=>{setSelectedListing(p);nav("product")};
 const openChat=p=>{setSelectedListing(p);nav("messages")};
 const logout=async()=>{if(supabase)await supabase.auth.signOut();nav("home")};
 return <div className="app">
  <header><div className="nav">
   <button className="brand" onClick={()=>nav("home")}><span className="brandmark">C</span> CampusMarket</button>
   <nav className={menu?"open":""}><button onClick={()=>nav("marketplace")}>Marketplace</button><button onClick={()=>nav("home")}>How It Works</button><button onClick={()=>nav("messages")}><MessageCircle size={17}/> Messages</button>{user?<button className="ghost" onClick={logout}><LogOut size={16}/> Logout</button>:<button className="ghost" onClick={()=>nav("login")}>Login</button>}<button className="primary small" onClick={()=>nav("sell")}><Plus size={17}/> Sell an Item</button></nav>
   <button className="mobile" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>
  </div></header>

  {page==="home"&&<><section className="hero"><div><div className="eyebrow"><ShieldCheck size={16}/> Student-first marketplace</div><h1>Your Campus<br/><span>Marketplace.</span></h1><p>Buy what you need. Sell what you no longer need. Connect with students around you.</p><div className="actions"><button className="primary" onClick={()=>nav("marketplace")}>Browse Marketplace <ArrowRight size={18}/></button><button className="secondary" onClick={()=>nav("sell")}>Start Selling</button></div><div className="trust"><ShieldCheck size={17}/> Built with secure accounts, moderation and private buyer-seller conversations.</div></div><div className="hero-card"><div className="floating">🔥 Trending on campus</div><img src={demo[0].image}/><div className="hero-product"><div><b>Vintage Denim Jacket</b><small>Thrift/Fashion · LASU</small></div><strong>₦8,000</strong></div></div></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">Explore</span><h2>Shop by category</h2></div></div><div className="categories">{cats.slice(1).map(c=><button key={c} onClick={()=>{setCategory(c);nav("marketplace")}}><Tag size={19}/>{c}</button>)}</div></section>
  <section className="section"><div className="section-head"><div><span className="eyebrow">Fresh listings</span><h2>Featured products</h2></div><button className="text-btn" onClick={()=>nav("marketplace")}>View all <ArrowRight size={16}/></button></div><div className="grid">{products.map(p=><ProductCard key={p.id} p={p} fav={favorites.includes(p.id)} toggle={()=>setFavorites(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])} open={()=>openProduct(p)}/>)}</div></section>
  <section className="how"><div className="section"><span className="eyebrow">Simple process</span><h2>Buy and sell without the clutter.</h2><div className="steps"><Step n="01" title="Create an account" text="Join the student community and build your profile."/><Step n="02" title="List or discover" text="Upload thrift, electronics, books and other campus essentials."/><Step n="03" title="Chat & negotiate" text="Message sellers and bargain on the price before agreeing." /></div></div></section></>}

  {page==="marketplace"&&<section className="section page"><div className="page-title"><span className="eyebrow">Marketplace</span><h1>Find something worth buying.</h1><p>Search campus listings and discover great deals.</p></div><div className="searchbar"><Search size={20}/><input placeholder="Search products..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="chips">{cats.map(c=><button className={category===c?"active":""} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><div className="grid">{filtered.map(p=><ProductCard key={p.id} p={p} fav={favorites.includes(p.id)} toggle={()=>setFavorites(f=>f.includes(p.id)?f.filter(x=>x!==p.id):[...f,p.id])} open={()=>openProduct(p)}/>)}</div>{!filtered.length&&<div className="empty">No products found. Try another search.</div>}</section>}

  {page==="product"&&selectedListing&&<ProductDetail p={selectedListing} back={()=>nav("marketplace")} message={()=>openChat(selectedListing)}/>} 
  {page==="sell"&&<Sell onAdd={async()=>{await loadListings();nav("marketplace")}}/>}
  {page==="messages"&&<Messages listing={selectedListing} onBack={()=>nav("marketplace")}/>} 
  {page==="login"&&<Auth onSuccess={()=>nav("marketplace")}/>} 
  <footer><b>CampusMarket</b><span>Buy. Sell. Connect. On Campus.</span><span>© 2026 CampusMarket</span></footer>
 </div>
}
function ProductCard({p,fav,toggle,open}){return <article className="card"><div className="pic"><img src={p.image||demo[0].image}/><button className={"heart "+(fav?"liked":"")} onClick={toggle}><Heart size={18} fill={fav?"currentColor":"none"}/></button><span>{p.condition}</span></div><div className="cardbody"><small>{p.category}</small><h3>{p.title}</h3><div className="row"><strong>₦{p.price.toLocaleString()}</strong><small>{p.location}</small></div><button className="view" onClick={open}>View item</button></div></article>}
function Step({n,title,text}){return <div className="step"><b>{n}</b><h3>{title}</h3><p>{text}</p></div>}
function ProductDetail({p,back,message}){return <section className="section page detail"><button className="back" onClick={back}>← Back to marketplace</button><div className="detailgrid"><img className="detailimg" src={p.image||demo[0].image}/><div><span className="eyebrow">{p.category}</span><h1>{p.title}</h1><div className="bigprice">₦{p.price.toLocaleString()}</div><p>{p.description||"No description provided by the seller."}</p><div className="seller"><div className="avatar">{(p.seller||"S")[0].toUpperCase()}</div><div><b>{p.seller||"Seller"}</b><small>{p.location}</small></div></div><div className="actions"><button className="primary" onClick={message}><MessageCircle size={18}/> Message Seller</button><button className="secondary">♡ Add to Favorites</button></div><div className="safety"><ShieldCheck/> Never share passwords or verification codes. Meet in appropriate public places and be cautious with suspicious payment requests.</div></div></div></section>}
function Sell({onAdd}){const [name,setName]=useState(""),[price,setPrice]=useState(""),[cat,setCat]=useState("Thrift/Fashion"),[description,setDescription]=useState(""),[location,setLocation]=useState("");return <section className="section page formpage"><span className="eyebrow">Create listing</span><h1>Sell an item</h1><p>Give another student a chance to find something useful.</p><div className="form"><label>Item name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Vintage Denim Jacket"/></label><label>Price (₦)<input type="number" value={price} onChange={e=>setPrice(e.target.value)} placeholder="8000"/></label><label>Category<select value={cat} onChange={e=>setCat(e.target.value)}><option>Thrift/Fashion</option><option>Electronics</option><option>Books</option><option>School Supplies</option><option>Accessories</option><option>Food</option><option>Accommodation</option><option>Services</option></select></label><label>General location<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="e.g. LASU / Oto-Ijanikin"/></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the item, condition and anything a buyer should know."/></label><div className="upload">📸<b>Product photos</b><span>Image upload can be connected to your existing Supabase Storage bucket.</span></div><button className="primary" disabled={!name||!price||!supabase} onClick={async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){alert("Please log in first.");return;}const {error}=await supabase.from("listings").insert({title:name,price:Number(price),category:cat,description,location,seller_id:user.id}).select().single();if(error)alert(error.message);else onAdd();}}>Publish Listing <ArrowRight size={18}/></button></div></section>}

function Messages({listing,onBack}){
 const [user,setUser]=useState(null),[loading,setLoading]=useState(true),[text,setText]=useState(""),[messages,setMessages]=useState([]),[error,setError]=useState(""),[sellerName,setSellerName]=useState("Seller");
 const listingId=listing?.id, sellerId=listing?.seller_id;
 useEffect(()=>{if(!supabase){setError("Supabase is not connected. Add your project URL and public anon/publishable key to .env.");setLoading(false);return;}supabase.auth.getUser().then(({data})=>{setUser(data.user||null);setLoading(false);});},[]);
 useEffect(()=>{if(!supabase||!user||!listingId||!sellerId)return;let mounted=true;const load=async()=>{const {data,error}=await supabase.from("messages").select("*").eq("listing_id",listingId).or(`sender_id.eq.${user.id},receiver_id.eq.${user.id}`).order("created_at",{ascending:true});if(mounted){if(error)setError(error.message);else setMessages(data||[]);}};load();
   const loadSeller=async()=>{const {data}=await supabase.from("profiles").select("full_name,name,username").eq("id",sellerId).maybeSingle();if(data)setSellerName(first(data.full_name,data.name,data.username,listing?.seller,"Seller"));else if(listing?.seller)setSellerName(listing.seller);};loadSeller();
   const channel=supabase.channel(`listing-chat:${listingId}:${user.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`listing_id=eq.${listingId}`},payload=>{const m=payload.new;if((m.sender_id===user.id&&m.receiver_id===sellerId)||(m.sender_id===sellerId&&m.receiver_id===user.id))setMessages(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]);}).subscribe();return()=>{mounted=false;supabase.removeChannel(channel)};
 },[user,listingId,sellerId]);
 const send=async()=>{const content=text.trim();if(!content||!user||!listingId||!sellerId||!supabase)return;setError("");if(sellerId===user.id){setError("You cannot message yourself about your own listing.");return;}const {data,error}=await supabase.from("messages").insert({listing_id:listingId,sender_id:user.id,receiver_id:sellerId,content}).select().single();if(error)setError(error.message);else{setText("");setMessages(prev=>prev.some(m=>m.id===data.id)?prev:[...prev,data]);}};
 if(loading)return <section className="section page"><span className="eyebrow">Messages</span><h1>Loading chat…</h1></section>;
 if(!user)return <section className="section page"><span className="eyebrow">Messages</span><h1>Sign in to chat</h1><p>You need a CampusMarket account before you can message a seller.</p></section>;
 if(!listingId||!sellerId)return <section className="section page"><span className="eyebrow">Messages</span><h1>Select a real listing</h1><p>Open a Supabase listing and press <b>Message Seller</b>. That supplies the real listing ID and seller account ID.</p><button className="primary" onClick={onBack}>Browse Marketplace</button></section>;
 return <section className="section page"><button className="back" onClick={onBack}>← Back to marketplace</button><span className="eyebrow">Messages</span><h1>Chat & negotiate</h1><p>Conversation about <b>{listing.title}</b> · ₦{listing.price.toLocaleString()}</p><div className="chat"><div className="chathead"><div className="avatar">{sellerName[0]?.toUpperCase()}</div><div><b>{sellerName}</b><small>{listing.location||"Campus"}</small></div></div><div className="chatbody">{messages.length===0&&<div className="empty">No messages yet. Start the conversation.</div>}{messages.map(m=><div key={m.id} className={"bubble "+(m.sender_id===user.id?"mine":"other")}>{m.content}</div>)}</div>{error&&<div className="chat-error">{error}</div>}<div className="chatinput"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")send()}} placeholder="Write a message..."/><button className="primary" onClick={send}>Send</button></div></div></section>
}
function Auth({onSuccess}){const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[mode,setMode]=useState("login"),[name,setName]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async()=>{if(!supabase){setError("Connect Supabase in .env first.");return;}setBusy(true);setError("");if(mode==="login"){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setError(error.message);else onSuccess();}else{const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)setError(error.message);else if(data.user&&!data.session)setError("Account created. Check your email to confirm your account, then log in.");else onSuccess();}setBusy(false)};return <section className="section page formpage"><div className="auth"><span className="eyebrow">Welcome</span><h1>{mode==="login"?"Welcome back":"Create your account"}</h1><p>{mode==="login"?"Sign in to message sellers and manage listings.":"Join CampusMarket today."}</p><div className="form">{mode==="signup"&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your full name"/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/></label>{error&&<div className="chat-error">{error}</div>}<button className="primary" disabled={busy||!email||!password} onClick={submit}>{busy?"Please wait…":mode==="login"?"Log in":"Create account"} <ArrowRight size={18}/></button><button className="text-btn" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"Need an account? Sign up":"Already have an account? Log in"}</button></div></div></section>}
createRoot(document.getElementById("root")).render(<App/>);
